/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdDStandardEspos;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdDStandardEsposDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * SipraMtdDStandardEspos DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdDStandardEsposDAOImpl extends GenericDAO<SipraMtdDStandardEspos> implements SipraMtdDStandardEsposDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdDStandardEsposDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from sipra_mtd_d_standard_espos where id_standard_espos = :id_standard_espos";
	
	private final static String QUERY_INSERT = 
		"insert into sipra_mtd_d_standard_espos(id_standard_espos,des_standard_espos) values(:id_standard_espos,:des_standard_espos)";

	private final static String QUERY_UPDATE = 
		"update sipra_mtd_d_standard_espos set des_standard_espos = :des_standard_espos  where id_standard_espos = :id_standard_espos";

	private final static String QUERY_DELETE = 
		"delete from sipra_mtd_d_standard_espos where  id_standard_espos = :id_standard_espos";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from sipra_mtd_d_standard_espos";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "sipra_mtd_d_standard_espos";
	}

	@Override
	public String getSqlSelect() {
		return "select * from sipra_mtd_d_standard_espos";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdDStandardEspos findByPK(Integer idStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_espos", idStandardEspos);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_espos", idStandardEspos);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdDStandardEspos sipraMtdDStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_espos", sipraMtdDStandardEspos.getIdStandardEspos());
		map.put("des_standard_espos", sipraMtdDStandardEspos.getDesStandardEspos());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdDStandardEspos sipraMtdDStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("des_standard_espos", sipraMtdDStandardEspos.getDesStandardEspos());
		map.put("id_standard_espos", sipraMtdDStandardEspos.getIdStandardEspos());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdDStandardEspos sipraMtdDStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_espos", sipraMtdDStandardEspos.getIdStandardEspos());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdDStandardEspos sipraMtdDStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_espos", sipraMtdDStandardEspos.getIdStandardEspos());
		return map;
	}

	@Override
	public RowMapper<SipraMtdDStandardEspos> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdDStandardEsposRowMapper( new SipraMtdDStandardEspos() ) ;

       return new SipraMtdDStandardEsposRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdDStandardEspos
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdDStandardEspos sipraMtdDStandardEspos) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdDStandardEspos.setIdStandardEspos(rs.getInt("id_standard_espos")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdDStandardEspos.setIdStandardEspos(null); }; // not primitive number => keep null value if any
		sipraMtdDStandardEspos.setDesStandardEspos(rs.getString("des_standard_espos")); // java.lang.String
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdDStandardEsposRowMapper implements RowMapper<SipraMtdDStandardEspos> {
	
		public SipraMtdDStandardEsposRowMapper() {
			
		}
		
		public SipraMtdDStandardEspos mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdDStandardEspos bean = new SipraMtdDStandardEspos();
			populateBean(rs, bean);
			return bean;
		}
	}
}
