/*
 * Created on 18 nov 2016 ( Time 17:08:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTMtdPlus;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTMtdPlusDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * SipraMtdTMtdPlus DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdTMtdPlusDAOImpl extends GenericDAO<SipraMtdTMtdPlus> implements SipraMtdTMtdPlusDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdTMtdPlusDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from sipra_mtd_t_mtd_plus where id_metadato = :id_metadato";
	
	private final static String QUERY_INSERT = 
		"insert into sipra_mtd_t_mtd_plus(id_metadato,nr_oggetti_dataset_calc,fk_tipo_oggetto) values(:id_metadato,:nr_oggetti_dataset_calc,:fk_tipo_oggetto)";

	private final static String QUERY_UPDATE = 
		"update sipra_mtd_t_mtd_plus set nr_oggetti_dataset_calc = :nr_oggetti_dataset_calc, fk_tipo_oggetto = :fk_tipo_oggetto  where id_metadato = :id_metadato";

	private final static String QUERY_DELETE = 
		"delete from sipra_mtd_t_mtd_plus where  id_metadato = :id_metadato";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from sipra_mtd_t_mtd_plus";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "sipra_mtd_t_mtd_plus";
	}

	@Override
	public String getSqlSelect() {
		return "select * from sipra_mtd_t_mtd_plus";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdTMtdPlus findByPK(Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", idMetadato);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", idMetadato);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdTMtdPlus sipraMtdTMtdPlus) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdTMtdPlus.getIdMetadato());
		map.put("nr_oggetti_dataset_calc", sipraMtdTMtdPlus.getNrOggettiDatasetCalc());
		map.put("fk_tipo_oggetto", sipraMtdTMtdPlus.getFkTipoOggetto());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdTMtdPlus sipraMtdTMtdPlus) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("nr_oggetti_dataset_calc", sipraMtdTMtdPlus.getNrOggettiDatasetCalc());
		map.put("fk_tipo_oggetto", sipraMtdTMtdPlus.getFkTipoOggetto());
		map.put("id_metadato", sipraMtdTMtdPlus.getIdMetadato());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdTMtdPlus sipraMtdTMtdPlus) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdTMtdPlus.getIdMetadato());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdTMtdPlus sipraMtdTMtdPlus) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdTMtdPlus.getIdMetadato());
		return map;
	}

	@Override
	public RowMapper<SipraMtdTMtdPlus> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdTMtdPlusRowMapper( new SipraMtdTMtdPlus() ) ;

       return new SipraMtdTMtdPlusRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdTMtdPlus
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdTMtdPlus sipraMtdTMtdPlus) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdTMtdPlus.setIdMetadato(rs.getInt("id_metadato")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdTMtdPlus.setIdMetadato(null); }; // not primitive number => keep null value if any
		sipraMtdTMtdPlus.setNrOggettiDatasetCalc(rs.getInt("nr_oggetti_dataset_calc")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdTMtdPlus.setNrOggettiDatasetCalc(null); }; // not primitive number => keep null value if any
		sipraMtdTMtdPlus.setFkTipoOggetto(rs.getInt("fk_tipo_oggetto")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdTMtdPlus.setFkTipoOggetto(null); }; // not primitive number => keep null value if any
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdTMtdPlusRowMapper implements RowMapper<SipraMtdTMtdPlus> {
	
		public SipraMtdTMtdPlusRowMapper() {
			
		}
		
		public SipraMtdTMtdPlus mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdTMtdPlus bean = new SipraMtdTMtdPlus();
			populateBean(rs, bean);
			return bean;
		}
	}
}
