/*
 * Created on 18 nov 2016 ( Time 17:08:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTMtdCsw;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTMtdCswDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * SipraMtdTMtdCsw DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdTMtdCswDAOImpl extends GenericDAO<SipraMtdTMtdCsw> implements SipraMtdTMtdCswDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdTMtdCswDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from sipra_mtd_t_mtd_csw where id_metadato = :id_metadato";
	
	private final static String QUERY_INSERT = 
		"insert into sipra_mtd_t_mtd_csw(id_metadato,dc_identifier,titolo,testo_abstract,tipo_metadato,url_metadato_calc,bound_box_crs,bound_box_lower_corner,bound_box_upper_corner) values(:id_metadato,:dc_identifier,:titolo,:testo_abstract,:tipo_metadato,:url_metadato_calc,:bound_box_crs,:bound_box_lower_corner,:bound_box_upper_corner)";

	private final static String QUERY_UPDATE = 
		"update sipra_mtd_t_mtd_csw set dc_identifier = :dc_identifier, titolo = :titolo, testo_abstract = :testo_abstract, tipo_metadato = :tipo_metadato, url_metadato_calc = :url_metadato_calc, bound_box_crs = :bound_box_crs, bound_box_lower_corner = :bound_box_lower_corner, bound_box_upper_corner = :bound_box_upper_corner  where id_metadato = :id_metadato";

	private final static String QUERY_DELETE = 
		"delete from sipra_mtd_t_mtd_csw where  id_metadato = :id_metadato";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from sipra_mtd_t_mtd_csw";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "sipra_mtd_t_mtd_csw";
	}

	@Override
	public String getSqlSelect() {
		return "select * from sipra_mtd_t_mtd_csw";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdTMtdCsw findByPK(Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", idMetadato);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", idMetadato);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdTMtdCsw sipraMtdTMtdCsw) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdTMtdCsw.getIdMetadato());
		map.put("dc_identifier", sipraMtdTMtdCsw.getDcIdentifier());
		map.put("titolo", sipraMtdTMtdCsw.getTitolo());
		map.put("testo_abstract", sipraMtdTMtdCsw.getTestoAbstract());
		map.put("tipo_metadato", sipraMtdTMtdCsw.getTipoMetadato());
		map.put("url_metadato_calc", sipraMtdTMtdCsw.getUrlMetadatoCalc());
		map.put("bound_box_crs", sipraMtdTMtdCsw.getBoundBoxCrs());
		map.put("bound_box_lower_corner", sipraMtdTMtdCsw.getBoundBoxLowerCorner());
		map.put("bound_box_upper_corner", sipraMtdTMtdCsw.getBoundBoxUpperCorner());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdTMtdCsw sipraMtdTMtdCsw) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("dc_identifier", sipraMtdTMtdCsw.getDcIdentifier());
		map.put("titolo", sipraMtdTMtdCsw.getTitolo());
		map.put("testo_abstract", sipraMtdTMtdCsw.getTestoAbstract());
		map.put("tipo_metadato", sipraMtdTMtdCsw.getTipoMetadato());
		map.put("url_metadato_calc", sipraMtdTMtdCsw.getUrlMetadatoCalc());
		map.put("bound_box_crs", sipraMtdTMtdCsw.getBoundBoxCrs());
		map.put("bound_box_lower_corner", sipraMtdTMtdCsw.getBoundBoxLowerCorner());
		map.put("bound_box_upper_corner", sipraMtdTMtdCsw.getBoundBoxUpperCorner());
		map.put("id_metadato", sipraMtdTMtdCsw.getIdMetadato());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdTMtdCsw sipraMtdTMtdCsw) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdTMtdCsw.getIdMetadato());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdTMtdCsw sipraMtdTMtdCsw) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdTMtdCsw.getIdMetadato());
		return map;
	}

	@Override
	public RowMapper<SipraMtdTMtdCsw> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdTMtdCswRowMapper( new SipraMtdTMtdCsw() ) ;

       return new SipraMtdTMtdCswRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdTMtdCsw
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdTMtdCsw sipraMtdTMtdCsw) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdTMtdCsw.setIdMetadato(rs.getInt("id_metadato")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdTMtdCsw.setIdMetadato(null); }; // not primitive number => keep null value if any
		sipraMtdTMtdCsw.setDcIdentifier(rs.getString("dc_identifier")); // java.lang.String
		sipraMtdTMtdCsw.setTitolo(rs.getString("titolo")); // java.lang.String
		sipraMtdTMtdCsw.setTestoAbstract(rs.getString("testo_abstract")); // java.lang.String
		sipraMtdTMtdCsw.setTipoMetadato(rs.getString("tipo_metadato")); // java.lang.String
		sipraMtdTMtdCsw.setUrlMetadatoCalc(rs.getString("url_metadato_calc")); // java.lang.String
		sipraMtdTMtdCsw.setBoundBoxCrs(rs.getString("bound_box_crs")); // java.lang.String
		sipraMtdTMtdCsw.setBoundBoxLowerCorner(rs.getString("bound_box_lower_corner")); // java.lang.String
		sipraMtdTMtdCsw.setBoundBoxUpperCorner(rs.getString("bound_box_upper_corner")); // java.lang.String
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdTMtdCswRowMapper implements RowMapper<SipraMtdTMtdCsw> {
	
		public SipraMtdTMtdCswRowMapper() {
			
		}
		
		public SipraMtdTMtdCsw mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdTMtdCsw bean = new SipraMtdTMtdCsw();
			populateBean(rs, bean);
			return bean;
		}
	}
}
