/*
 * Created on 25 nov 2016 ( Time 10:35:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;


/**
 * Java bean for 'SipraMtdDTipoFunzione' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdDTipoFunzione implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_tipo_funzione int4 
    private Integer idTipoFunzione;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : des_tipo_funzione varchar 
    private String desTipoFunzione;

    // DB : protocollo varchar 
    private String protocollo;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdTipoFunzione( Integer idTipoFunzione ) {
        this.idTipoFunzione = idTipoFunzione ;
    }

    public Integer getIdTipoFunzione() {
        return this.idTipoFunzione;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesTipoFunzione( String desTipoFunzione ) {
        this.desTipoFunzione = desTipoFunzione;
    }
    public String getDesTipoFunzione() {
        return this.desTipoFunzione;
    }

    public void setProtocollo( String protocollo ) {
        this.protocollo = protocollo;
    }
    public String getProtocollo() {
        return this.protocollo;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoFunzione);
        sb.append("|");
        sb.append(desTipoFunzione);
        sb.append("|");
        sb.append(protocollo);
        return sb.toString(); 
    } 


}
