/*
 * Created on 8 nov 2016 ( Time 16:16:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;


/**
 * Java bean for 'SipraMtdTSottocategoria' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdTSottocategoria implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_sottocategoria int4 
    private Integer idSottocategoria;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : fk_padre int4 
    private Integer fkPadre;

    // DB : des_sottocategoria varchar 
    private String desSottocategoria;

    // DB : livello int4 
    private Integer livello;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdSottocategoria( Integer idSottocategoria ) {
        this.idSottocategoria = idSottocategoria ;
    }

    public Integer getIdSottocategoria() {
        return this.idSottocategoria;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setFkPadre( Integer fkPadre ) {
        this.fkPadre = fkPadre;
    }
    public Integer getFkPadre() {
        return this.fkPadre;
    }

    public void setDesSottocategoria( String desSottocategoria ) {
        this.desSottocategoria = desSottocategoria;
    }
    public String getDesSottocategoria() {
        return this.desSottocategoria;
    }

    public void setLivello( Integer livello ) {
        this.livello = livello;
    }
    public Integer getLivello() {
        return this.livello;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idSottocategoria);
        sb.append("|");
        sb.append(fkPadre);
        sb.append("|");
        sb.append(desSottocategoria);
        sb.append("|");
        sb.append(livello);
        return sb.toString(); 
    } 


}
