/*
 * Created on 25 nov 2016 ( Time 10:35:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'SipraMtdTNewsHomePage' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdTNewsHomePage implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_news int4 
    private Integer idNews;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : titolo_news varchar 
    private String titoloNews;

    // DB : abstract_news varchar 
    private String abstractNews;

    // DB : priorita numeric 
    private BigDecimal priorita;

    // DB : data_inizio date 
    private Date dataInizio;

    // DB : data_fine date 
    private Date dataFine;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdNews( Integer idNews ) {
        this.idNews = idNews ;
    }

    public Integer getIdNews() {
        return this.idNews;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTitoloNews( String titoloNews ) {
        this.titoloNews = titoloNews;
    }
    public String getTitoloNews() {
        return this.titoloNews;
    }

    public void setAbstractNews( String abstractNews ) {
        this.abstractNews = abstractNews;
    }
    public String getAbstractNews() {
        return this.abstractNews;
    }

    public void setPriorita( BigDecimal priorita ) {
        this.priorita = priorita;
    }
    public BigDecimal getPriorita() {
        return this.priorita;
    }

    public void setDataInizio( Date dataInizio ) {
        this.dataInizio = dataInizio;
    }
    public Date getDataInizio() {
        return this.dataInizio;
    }

    public void setDataFine( Date dataFine ) {
        this.dataFine = dataFine;
    }
    public Date getDataFine() {
        return this.dataFine;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idNews);
        sb.append("|");
        sb.append(titoloNews);
        sb.append("|");
        sb.append(abstractNews);
        sb.append("|");
        sb.append(priorita);
        sb.append("|");
        sb.append(dataInizio);
        sb.append("|");
        sb.append(dataFine);
        return sb.toString(); 
    } 


}
