/*
 * Created on 25 nov 2016 ( Time 10:35:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;


/**
 * Java bean for 'SipraMtdTParolaChiave' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdTParolaChiave implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_parola_chiave int4 
    private Integer idParolaChiave;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : des_parola_chiave varchar 
    private String desParolaChiave;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdParolaChiave( Integer idParolaChiave ) {
        this.idParolaChiave = idParolaChiave ;
    }

    public Integer getIdParolaChiave() {
        return this.idParolaChiave;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesParolaChiave( String desParolaChiave ) {
        this.desParolaChiave = desParolaChiave;
    }
    public String getDesParolaChiave() {
        return this.desParolaChiave;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idParolaChiave);
        sb.append("|");
        sb.append(desParolaChiave);
        return sb.toString(); 
    } 


}
