/*
 * Created on 25 nov 2016 ( Time 10:35:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;


/**
 * Java bean for 'SipraMtdTDettlog' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdTDettlog implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_dett_log int4 
    private Integer idDettLog;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : fk_log int4 
    private Integer fkLog;

    // DB : cod_errore varchar 
    private String codErrore;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdDettLog( Integer idDettLog ) {
        this.idDettLog = idDettLog ;
    }

    public Integer getIdDettLog() {
        return this.idDettLog;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setFkLog( Integer fkLog ) {
        this.fkLog = fkLog;
    }
    public Integer getFkLog() {
        return this.fkLog;
    }

    public void setCodErrore( String codErrore ) {
        this.codErrore = codErrore;
    }
    public String getCodErrore() {
        return this.codErrore;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idDettLog);
        sb.append("|");
        sb.append(fkLog);
        sb.append("|");
        sb.append(codErrore);
        return sb.toString(); 
    } 


}
