/*
 * Created on 25 nov 2016 ( Time 10:35:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'SipraMtdTTestiHomePage' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdTTestiHomePage implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_testo int4 
    private Integer idTesto;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : tipo_testo varchar 
    private String tipoTesto;

    // DB : titolo_testo varchar 
    private String titoloTesto;

    // DB : abstract_testo varchar 
    private String abstractTesto;

    // DB : data_inizio date 
    private Date dataInizio;

    // DB : data_fine date 
    private Date dataFine;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdTesto( Integer idTesto ) {
        this.idTesto = idTesto ;
    }

    public Integer getIdTesto() {
        return this.idTesto;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTipoTesto( String tipoTesto ) {
        this.tipoTesto = tipoTesto;
    }
    public String getTipoTesto() {
        return this.tipoTesto;
    }

    public void setTitoloTesto( String titoloTesto ) {
        this.titoloTesto = titoloTesto;
    }
    public String getTitoloTesto() {
        return this.titoloTesto;
    }

    public void setAbstractTesto( String abstractTesto ) {
        this.abstractTesto = abstractTesto;
    }
    public String getAbstractTesto() {
        return this.abstractTesto;
    }

    public void setDataInizio( Date dataInizio ) {
        this.dataInizio = dataInizio;
    }
    public Date getDataInizio() {
        return this.dataInizio;
    }

    public void setDataFine( Date dataFine ) {
        this.dataFine = dataFine;
    }
    public Date getDataFine() {
        return this.dataFine;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTesto);
        sb.append("|");
        sb.append(tipoTesto);
        sb.append("|");
        sb.append(titoloTesto);
        sb.append("|");
        sb.append(abstractTesto);
        sb.append("|");
        sb.append(dataInizio);
        sb.append("|");
        sb.append(dataFine);
        return sb.toString(); 
    } 


}
