/*
 * Created on 8 nov 2016 ( Time 16:16:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdRCategSottocateg;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdRCategSottocategDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * SipraMtdRCategSottocateg DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdRCategSottocategDAOImpl extends GenericDAO<SipraMtdRCategSottocateg> implements SipraMtdRCategSottocategDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdRCategSottocategDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from sipra_mtd_r_categ_sottocateg where id_categoria = :id_categoria and id_sottocategoria = :id_sottocategoria";
	
	private final static String QUERY_INSERT = 
		"insert into sipra_mtd_r_categ_sottocateg(id_categoria,id_sottocategoria) values(:id_categoria,:id_sottocategoria)";

	private final static String QUERY_UPDATE = 
		"update sipra_mtd_r_categ_sottocateg set   where id_categoria = :id_categoria and id_sottocategoria = :id_sottocategoria";

	private final static String QUERY_DELETE = 
		"delete from sipra_mtd_r_categ_sottocateg where  id_categoria = :id_categoria and id_sottocategoria = :id_sottocategoria";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from sipra_mtd_r_categ_sottocateg";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "sipra_mtd_r_categ_sottocateg";
	}

	@Override
	public String getSqlSelect() {
		return "select * from sipra_mtd_r_categ_sottocateg";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdRCategSottocateg findByPK(Integer idCategoria, Integer idSottocategoria) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_categoria", idCategoria);
		map.put("id_sottocategoria", idSottocategoria);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idCategoria, Integer idSottocategoria) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_categoria", idCategoria);
		map.put("id_sottocategoria", idSottocategoria);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdRCategSottocateg sipraMtdRCategSottocateg) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_categoria", sipraMtdRCategSottocateg.getIdCategoria());
		map.put("id_sottocategoria", sipraMtdRCategSottocateg.getIdSottocategoria());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdRCategSottocateg sipraMtdRCategSottocateg) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_categoria", sipraMtdRCategSottocateg.getIdCategoria());
		map.put("id_sottocategoria", sipraMtdRCategSottocateg.getIdSottocategoria());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdRCategSottocateg sipraMtdRCategSottocateg) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_categoria", sipraMtdRCategSottocateg.getIdCategoria());
		map.put("id_sottocategoria", sipraMtdRCategSottocateg.getIdSottocategoria());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdRCategSottocateg sipraMtdRCategSottocateg) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_categoria", sipraMtdRCategSottocateg.getIdCategoria());
		map.put("id_sottocategoria", sipraMtdRCategSottocateg.getIdSottocategoria());
		return map;
	}

	@Override
	public RowMapper<SipraMtdRCategSottocateg> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdRCategSottocategRowMapper( new SipraMtdRCategSottocateg() ) ;

       return new SipraMtdRCategSottocategRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdRCategSottocateg
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdRCategSottocateg sipraMtdRCategSottocateg) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdRCategSottocateg.setIdCategoria(rs.getInt("id_categoria")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdRCategSottocateg.setIdCategoria(null); }; // not primitive number => keep null value if any
		sipraMtdRCategSottocateg.setIdSottocategoria(rs.getInt("id_sottocategoria")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdRCategSottocateg.setIdSottocategoria(null); }; // not primitive number => keep null value if any
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdRCategSottocategRowMapper implements RowMapper<SipraMtdRCategSottocateg> {
	
		public SipraMtdRCategSottocategRowMapper() {
			
		}
		
		public SipraMtdRCategSottocateg mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdRCategSottocateg bean = new SipraMtdRCategSottocateg();
			populateBean(rs, bean);
			return bean;
		}
	}
}
