/*
 * Created on 8 nov 2016 ( Time 16:16:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdRSottocategMtd;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdRSottocategMtdDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * SipraMtdRSottocategMtd DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdRSottocategMtdDAOImpl extends GenericDAO<SipraMtdRSottocategMtd> implements SipraMtdRSottocategMtdDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdRSottocategMtdDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from sipra_mtd_r_sottocateg_mtd where id_metadato = :id_metadato and id_sottocategoria = :id_sottocategoria";
	
	private final static String QUERY_INSERT = 
		"insert into sipra_mtd_r_sottocateg_mtd(id_metadato,id_sottocategoria) values(:id_metadato,:id_sottocategoria)";

	private final static String QUERY_UPDATE = 
		"update sipra_mtd_r_sottocateg_mtd set   where id_metadato = :id_metadato and id_sottocategoria = :id_sottocategoria";

	private final static String QUERY_DELETE = 
		"delete from sipra_mtd_r_sottocateg_mtd where  id_metadato = :id_metadato and id_sottocategoria = :id_sottocategoria";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from sipra_mtd_r_sottocateg_mtd";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "sipra_mtd_r_sottocateg_mtd";
	}

	@Override
	public String getSqlSelect() {
		return "select * from sipra_mtd_r_sottocateg_mtd";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdRSottocategMtd findByPK(Integer idMetadato, Integer idSottocategoria) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", idMetadato);
		map.put("id_sottocategoria", idSottocategoria);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idMetadato, Integer idSottocategoria) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", idMetadato);
		map.put("id_sottocategoria", idSottocategoria);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdRSottocategMtd sipraMtdRSottocategMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdRSottocategMtd.getIdMetadato());
		map.put("id_sottocategoria", sipraMtdRSottocategMtd.getIdSottocategoria());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdRSottocategMtd sipraMtdRSottocategMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdRSottocategMtd.getIdMetadato());
		map.put("id_sottocategoria", sipraMtdRSottocategMtd.getIdSottocategoria());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdRSottocategMtd sipraMtdRSottocategMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdRSottocategMtd.getIdMetadato());
		map.put("id_sottocategoria", sipraMtdRSottocategMtd.getIdSottocategoria());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdRSottocategMtd sipraMtdRSottocategMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdRSottocategMtd.getIdMetadato());
		map.put("id_sottocategoria", sipraMtdRSottocategMtd.getIdSottocategoria());
		return map;
	}

	@Override
	public RowMapper<SipraMtdRSottocategMtd> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdRSottocategMtdRowMapper( new SipraMtdRSottocategMtd() ) ;

       return new SipraMtdRSottocategMtdRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdRSottocategMtd
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdRSottocategMtd sipraMtdRSottocategMtd) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdRSottocategMtd.setIdMetadato(rs.getInt("id_metadato")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdRSottocategMtd.setIdMetadato(null); }; // not primitive number => keep null value if any
		sipraMtdRSottocategMtd.setIdSottocategoria(rs.getInt("id_sottocategoria")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdRSottocategMtd.setIdSottocategoria(null); }; // not primitive number => keep null value if any
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdRSottocategMtdRowMapper implements RowMapper<SipraMtdRSottocategMtd> {
	
		public SipraMtdRSottocategMtdRowMapper() {
			
		}
		
		public SipraMtdRSottocategMtd mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdRSottocategMtd bean = new SipraMtdRSottocategMtd();
			populateBean(rs, bean);
			return bean;
		}
	}
}
