/*
 * Created on 25 nov 2016 ( Time 10:35:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdDLingua;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdDLinguaDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * SipraMtdDLingua DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdDLinguaDAOImpl extends GenericDAO<SipraMtdDLingua> implements SipraMtdDLinguaDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdDLinguaDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from sipra_mtd_d_lingua where id_lingua = :id_lingua";
	
	private final static String QUERY_INSERT = 
		"insert into sipra_mtd_d_lingua(id_lingua,des_lingua) values(:id_lingua,:des_lingua)";

	private final static String QUERY_UPDATE = 
		"update sipra_mtd_d_lingua set des_lingua = :des_lingua  where id_lingua = :id_lingua";

	private final static String QUERY_DELETE = 
		"delete from sipra_mtd_d_lingua where  id_lingua = :id_lingua";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from sipra_mtd_d_lingua";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "sipra_mtd_d_lingua";
	}

	@Override
	public String getSqlSelect() {
		return "select * from sipra_mtd_d_lingua";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdDLingua findByPK(Integer idLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_lingua", idLingua);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_lingua", idLingua);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdDLingua sipraMtdDLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_lingua", sipraMtdDLingua.getIdLingua());
		map.put("des_lingua", sipraMtdDLingua.getDesLingua());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdDLingua sipraMtdDLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("des_lingua", sipraMtdDLingua.getDesLingua());
		map.put("id_lingua", sipraMtdDLingua.getIdLingua());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdDLingua sipraMtdDLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_lingua", sipraMtdDLingua.getIdLingua());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdDLingua sipraMtdDLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_lingua", sipraMtdDLingua.getIdLingua());
		return map;
	}

	@Override
	public RowMapper<SipraMtdDLingua> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdDLinguaRowMapper( new SipraMtdDLingua() ) ;

       return new SipraMtdDLinguaRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdDLingua
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdDLingua sipraMtdDLingua) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdDLingua.setIdLingua(rs.getInt("id_lingua")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdDLingua.setIdLingua(null); }; // not primitive number => keep null value if any
		sipraMtdDLingua.setDesLingua(rs.getString("des_lingua")); // java.lang.String
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdDLinguaRowMapper implements RowMapper<SipraMtdDLingua> {
	
		public SipraMtdDLinguaRowMapper() {
			
		}
		
		public SipraMtdDLingua mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdDLingua bean = new SipraMtdDLingua();
			populateBean(rs, bean);
			return bean;
		}
	}
}
