/*
 * Created on 25 nov 2016 ( Time 10:35:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTMetadato;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTMetadatoDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;
import java.util.Date;

/**
 * SipraMtdTMetadato DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdTMetadatoDAOImpl extends GenericDAO<SipraMtdTMetadato> implements SipraMtdTMetadatoDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdTMetadatoDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from sipra_mtd_t_metadato where id_metadato = :id_metadato";
	
	private final static String QUERY_INSERT = 
		"insert into sipra_mtd_t_metadato(id_metadato,fk_fontedati,des_metadato,data_ult_agg) values(:id_metadato,:fk_fontedati,:des_metadato,:data_ult_agg)";

	private final static String QUERY_UPDATE = 
		"update sipra_mtd_t_metadato set fk_fontedati = :fk_fontedati, des_metadato = :des_metadato, data_ult_agg = :data_ult_agg  where id_metadato = :id_metadato";

	private final static String QUERY_DELETE = 
		"delete from sipra_mtd_t_metadato where  id_metadato = :id_metadato";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from sipra_mtd_t_metadato";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "sipra_mtd_t_metadato";
	}

	@Override
	public String getSqlSelect() {
		return "select * from sipra_mtd_t_metadato";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdTMetadato findByPK(Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", idMetadato);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", idMetadato);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdTMetadato sipraMtdTMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdTMetadato.getIdMetadato());
		map.put("fk_fontedati", sipraMtdTMetadato.getFkFontedati());
		map.put("des_metadato", sipraMtdTMetadato.getDesMetadato());
		map.put("data_ult_agg", sipraMtdTMetadato.getDataUltAgg());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdTMetadato sipraMtdTMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("fk_fontedati", sipraMtdTMetadato.getFkFontedati());
		map.put("des_metadato", sipraMtdTMetadato.getDesMetadato());
		map.put("data_ult_agg", sipraMtdTMetadato.getDataUltAgg());
		map.put("id_metadato", sipraMtdTMetadato.getIdMetadato());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdTMetadato sipraMtdTMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdTMetadato.getIdMetadato());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdTMetadato sipraMtdTMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadato", sipraMtdTMetadato.getIdMetadato());
		return map;
	}

	@Override
	public RowMapper<SipraMtdTMetadato> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdTMetadatoRowMapper( new SipraMtdTMetadato() ) ;

       return new SipraMtdTMetadatoRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdTMetadato
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdTMetadato sipraMtdTMetadato) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdTMetadato.setIdMetadato(rs.getInt("id_metadato")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdTMetadato.setIdMetadato(null); }; // not primitive number => keep null value if any
		sipraMtdTMetadato.setFkFontedati(rs.getInt("fk_fontedati")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdTMetadato.setFkFontedati(null); }; // not primitive number => keep null value if any
		sipraMtdTMetadato.setDesMetadato(rs.getString("des_metadato")); // java.lang.String
		sipraMtdTMetadato.setDataUltAgg(rs.getDate("data_ult_agg")); // java.util.Date
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdTMetadatoRowMapper implements RowMapper<SipraMtdTMetadato> {
	
		public SipraMtdTMetadatoRowMapper() {
			
		}
		
		public SipraMtdTMetadato mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdTMetadato bean = new SipraMtdTMetadato();
			populateBean(rs, bean);
			return bean;
		}
	}
}
