/*
 * Created on 25 nov 2016 ( Time 10:35:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTNewsHomePage;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTNewsHomePageDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;
import java.math.BigDecimal;
import java.util.Date;

/**
 * SipraMtdTNewsHomePage DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdTNewsHomePageDAOImpl extends GenericDAO<SipraMtdTNewsHomePage> implements SipraMtdTNewsHomePageDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdTNewsHomePageDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from sipra_mtd_t_news_home_page where id_news = :id_news";
	
	private final static String QUERY_INSERT = 
		"insert into sipra_mtd_t_news_home_page(id_news,titolo_news,abstract_news,priorita,data_inizio,data_fine) values(:id_news,:titolo_news,:abstract_news,:priorita,:data_inizio,:data_fine)";

	private final static String QUERY_UPDATE = 
		"update sipra_mtd_t_news_home_page set titolo_news = :titolo_news, abstract_news = :abstract_news, priorita = :priorita, data_inizio = :data_inizio, data_fine = :data_fine  where id_news = :id_news";

	private final static String QUERY_DELETE = 
		"delete from sipra_mtd_t_news_home_page where  id_news = :id_news";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from sipra_mtd_t_news_home_page";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "sipra_mtd_t_news_home_page";
	}

	@Override
	public String getSqlSelect() {
		return "select * from sipra_mtd_t_news_home_page";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdTNewsHomePage findByPK(Integer idNews) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_news", idNews);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idNews) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_news", idNews);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdTNewsHomePage sipraMtdTNewsHomePage) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_news", sipraMtdTNewsHomePage.getIdNews());
		map.put("titolo_news", sipraMtdTNewsHomePage.getTitoloNews());
		map.put("abstract_news", sipraMtdTNewsHomePage.getAbstractNews());
		map.put("priorita", sipraMtdTNewsHomePage.getPriorita());
		map.put("data_inizio", sipraMtdTNewsHomePage.getDataInizio());
		map.put("data_fine", sipraMtdTNewsHomePage.getDataFine());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdTNewsHomePage sipraMtdTNewsHomePage) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("titolo_news", sipraMtdTNewsHomePage.getTitoloNews());
		map.put("abstract_news", sipraMtdTNewsHomePage.getAbstractNews());
		map.put("priorita", sipraMtdTNewsHomePage.getPriorita());
		map.put("data_inizio", sipraMtdTNewsHomePage.getDataInizio());
		map.put("data_fine", sipraMtdTNewsHomePage.getDataFine());
		map.put("id_news", sipraMtdTNewsHomePage.getIdNews());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdTNewsHomePage sipraMtdTNewsHomePage) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_news", sipraMtdTNewsHomePage.getIdNews());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdTNewsHomePage sipraMtdTNewsHomePage) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_news", sipraMtdTNewsHomePage.getIdNews());
		return map;
	}

	@Override
	public RowMapper<SipraMtdTNewsHomePage> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdTNewsHomePageRowMapper( new SipraMtdTNewsHomePage() ) ;

       return new SipraMtdTNewsHomePageRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdTNewsHomePage
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdTNewsHomePage sipraMtdTNewsHomePage) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdTNewsHomePage.setIdNews(rs.getInt("id_news")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdTNewsHomePage.setIdNews(null); }; // not primitive number => keep null value if any
		sipraMtdTNewsHomePage.setTitoloNews(rs.getString("titolo_news")); // java.lang.String
		sipraMtdTNewsHomePage.setAbstractNews(rs.getString("abstract_news")); // java.lang.String
		sipraMtdTNewsHomePage.setPriorita(rs.getBigDecimal("priorita")); // java.math.BigDecimal
		if ( rs.wasNull() ) { sipraMtdTNewsHomePage.setPriorita(null); }; // not primitive number => keep null value if any
		sipraMtdTNewsHomePage.setDataInizio(rs.getDate("data_inizio")); // java.util.Date
		sipraMtdTNewsHomePage.setDataFine(rs.getDate("data_fine")); // java.util.Date
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdTNewsHomePageRowMapper implements RowMapper<SipraMtdTNewsHomePage> {
	
		public SipraMtdTNewsHomePageRowMapper() {
			
		}
		
		public SipraMtdTNewsHomePage mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdTNewsHomePage bean = new SipraMtdTNewsHomePage();
			populateBean(rs, bean);
			return bean;
		}
	}
}
