/*
 * Created on 18 nov 2016 ( Time 17:08:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTParolaChiave;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * SipraMtdTParolaChiave DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdTParolaChiaveDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idParolaChiave
	 * @return the bean found or null if not found 
	 */
	public SipraMtdTParolaChiave findByPK(Integer idParolaChiave);

	public List<SipraMtdTParolaChiave> findAll();
	
	public List<SipraMtdTParolaChiave> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdTParolaChiave> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdTParolaChiave> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdTParolaChiave bean);

	public void update(SipraMtdTParolaChiave bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idParolaChiave);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdTParolaChiave> getRowMapper();
}
