/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTMetadato;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;


import java.util.Date;


/**
 * SipraMtdTMetadato DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdTMetadatoDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idMetadato
	 * @return the bean found or null if not found 
	 */
	public SipraMtdTMetadato findByPK(Integer idMetadato);

	public List<SipraMtdTMetadato> findAll();
	
	public List<SipraMtdTMetadato> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdTMetadato> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdTMetadato> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdTMetadato bean);

	public void update(SipraMtdTMetadato bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idMetadato);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdTMetadato> getRowMapper();
}
