/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdDTipoCategoria;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * SipraMtdDTipoCategoria DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdDTipoCategoriaDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idTipoCategoria
	 * @return the bean found or null if not found 
	 */
	public SipraMtdDTipoCategoria findByPK(Integer idTipoCategoria);

	public List<SipraMtdDTipoCategoria> findAll();
	
	public List<SipraMtdDTipoCategoria> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdDTipoCategoria> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdDTipoCategoria> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdDTipoCategoria bean);

	public void update(SipraMtdDTipoCategoria bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idTipoCategoria);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdDTipoCategoria> getRowMapper();
}
