/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdDTipoOggetto;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * SipraMtdDTipoOggetto DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdDTipoOggettoDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idTipoOggetto
	 * @return the bean found or null if not found 
	 */
	public SipraMtdDTipoOggetto findByPK(Integer idTipoOggetto);

	public List<SipraMtdDTipoOggetto> findAll();
	
	public List<SipraMtdDTipoOggetto> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdDTipoOggetto> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdDTipoOggetto> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdDTipoOggetto bean);

	public void update(SipraMtdDTipoOggetto bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idTipoOggetto);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdDTipoOggetto> getRowMapper();
}
