/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdDTipoFunzione;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * SipraMtdDTipoFunzione DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdDTipoFunzioneDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idTipoFunzione
	 * @return the bean found or null if not found 
	 */
	public SipraMtdDTipoFunzione findByPK(Integer idTipoFunzione);

	public List<SipraMtdDTipoFunzione> findAll();
	
	public List<SipraMtdDTipoFunzione> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdDTipoFunzione> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdDTipoFunzione> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdDTipoFunzione bean);

	public void update(SipraMtdDTipoFunzione bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idTipoFunzione);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdDTipoFunzione> getRowMapper();
}
