/*
 * Created on 8 nov 2016 ( Time 16:16:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdRSottocategMtd;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * SipraMtdRSottocategMtd DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdRSottocategMtdDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idMetadato
	 * @param idSottocategoria
	 * @return the bean found or null if not found 
	 */
	public SipraMtdRSottocategMtd findByPK(Integer idMetadato, Integer idSottocategoria);

	public List<SipraMtdRSottocategMtd> findAll();
	
	public List<SipraMtdRSottocategMtd> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdRSottocategMtd> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdRSottocategMtd> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdRSottocategMtd bean);

	public void update(SipraMtdRSottocategMtd bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idMetadato, Integer idSottocategoria);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdRSottocategMtd> getRowMapper();
}
