/*
 * Created on 8 nov 2016 ( Time 16:16:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTSottocategoria;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * SipraMtdTSottocategoria DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdTSottocategoriaDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idSottocategoria
	 * @return the bean found or null if not found 
	 */
	public SipraMtdTSottocategoria findByPK(Integer idSottocategoria);

	public List<SipraMtdTSottocategoria> findAll();
	
	public List<SipraMtdTSottocategoria> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdTSottocategoria> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdTSottocategoria> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdTSottocategoria bean);

	public void update(SipraMtdTSottocategoria bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idSottocategoria);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdTSottocategoria> getRowMapper();
}
