/*
 * Created on 25 nov 2016 ( Time 10:35:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.utils;

// CUSTOM BEGIN
import it.csi.sira.backend.metadata.integration.custom.dao.InfoBoxDAO;

// CUSTOM END

import it.csi.sira.backend.metadata.integration.dao.SipraMtdDFontedatiDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdDLinguaDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdDStandardEsposDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdDTipoCategoriaDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdDTipoFunzioneDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdDTipoOggettoDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdRCategLinguaDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdRCategappCategoriDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdRCategoriaMtdDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdRParolachiaveMtdDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTCategoriaDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTCategoriaApplDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTDettlogDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTFunzioneDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTLogDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTMetadatoDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTMtdCswDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTMtdPlusDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTNewsHomePageDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTParolaChiaveDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTStoricoFunzioneDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTStoricoMtdCswDAO;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdTTestiHomePageDAO;

public class DAOManager 
{

 private SipraMtdDFontedatiDAO sipraMtdDFontedatiDAO;
 private SipraMtdDLinguaDAO sipraMtdDLinguaDAO;
 private SipraMtdDStandardEsposDAO sipraMtdDStandardEsposDAO;
 private SipraMtdDTipoCategoriaDAO sipraMtdDTipoCategoriaDAO;
 private SipraMtdDTipoFunzioneDAO sipraMtdDTipoFunzioneDAO;
 private SipraMtdDTipoOggettoDAO sipraMtdDTipoOggettoDAO;
 private SipraMtdRCategLinguaDAO sipraMtdRCategLinguaDAO;
 private SipraMtdRCategappCategoriDAO sipraMtdRCategappCategoriDAO;
 private SipraMtdRCategoriaMtdDAO sipraMtdRCategoriaMtdDAO;
 private SipraMtdRParolachiaveMtdDAO sipraMtdRParolachiaveMtdDAO;
 private SipraMtdTCategoriaDAO sipraMtdTCategoriaDAO;
 private SipraMtdTCategoriaApplDAO sipraMtdTCategoriaApplDAO;
 private SipraMtdTDettlogDAO sipraMtdTDettlogDAO;
 private SipraMtdTFunzioneDAO sipraMtdTFunzioneDAO;
 private SipraMtdTLogDAO sipraMtdTLogDAO;
 private SipraMtdTMetadatoDAO sipraMtdTMetadatoDAO;
 private SipraMtdTMtdCswDAO sipraMtdTMtdCswDAO;
 private SipraMtdTMtdPlusDAO sipraMtdTMtdPlusDAO;
 private SipraMtdTNewsHomePageDAO sipraMtdTNewsHomePageDAO;
 private SipraMtdTParolaChiaveDAO sipraMtdTParolaChiaveDAO;
 private SipraMtdTStoricoFunzioneDAO sipraMtdTStoricoFunzioneDAO;
 private SipraMtdTStoricoMtdCswDAO sipraMtdTStoricoMtdCswDAO;
 private SipraMtdTTestiHomePageDAO sipraMtdTTestiHomePageDAO;

 public void setSipraMtdDFontedatiDAO(SipraMtdDFontedatiDAO sipraMtdDFontedatiDAO)
 {
  this.sipraMtdDFontedatiDAO = sipraMtdDFontedatiDAO;
 }

 public SipraMtdDFontedatiDAO getSipraMtdDFontedatiDAO()
 {
  return this.sipraMtdDFontedatiDAO;
 }

 public void setSipraMtdDLinguaDAO(SipraMtdDLinguaDAO sipraMtdDLinguaDAO)
 {
  this.sipraMtdDLinguaDAO = sipraMtdDLinguaDAO;
 }

 public SipraMtdDLinguaDAO getSipraMtdDLinguaDAO()
 {
  return this.sipraMtdDLinguaDAO;
 }

 public void setSipraMtdDStandardEsposDAO(SipraMtdDStandardEsposDAO sipraMtdDStandardEsposDAO)
 {
  this.sipraMtdDStandardEsposDAO = sipraMtdDStandardEsposDAO;
 }

 public SipraMtdDStandardEsposDAO getSipraMtdDStandardEsposDAO()
 {
  return this.sipraMtdDStandardEsposDAO;
 }

 public void setSipraMtdDTipoCategoriaDAO(SipraMtdDTipoCategoriaDAO sipraMtdDTipoCategoriaDAO)
 {
  this.sipraMtdDTipoCategoriaDAO = sipraMtdDTipoCategoriaDAO;
 }

 public SipraMtdDTipoCategoriaDAO getSipraMtdDTipoCategoriaDAO()
 {
  return this.sipraMtdDTipoCategoriaDAO;
 }

 public void setSipraMtdDTipoFunzioneDAO(SipraMtdDTipoFunzioneDAO sipraMtdDTipoFunzioneDAO)
 {
  this.sipraMtdDTipoFunzioneDAO = sipraMtdDTipoFunzioneDAO;
 }

 public SipraMtdDTipoFunzioneDAO getSipraMtdDTipoFunzioneDAO()
 {
  return this.sipraMtdDTipoFunzioneDAO;
 }

 public void setSipraMtdDTipoOggettoDAO(SipraMtdDTipoOggettoDAO sipraMtdDTipoOggettoDAO)
 {
  this.sipraMtdDTipoOggettoDAO = sipraMtdDTipoOggettoDAO;
 }

 public SipraMtdDTipoOggettoDAO getSipraMtdDTipoOggettoDAO()
 {
  return this.sipraMtdDTipoOggettoDAO;
 }

 public void setSipraMtdRCategLinguaDAO(SipraMtdRCategLinguaDAO sipraMtdRCategLinguaDAO)
 {
  this.sipraMtdRCategLinguaDAO = sipraMtdRCategLinguaDAO;
 }

 public SipraMtdRCategLinguaDAO getSipraMtdRCategLinguaDAO()
 {
  return this.sipraMtdRCategLinguaDAO;
 }

 public void setSipraMtdRCategappCategoriDAO(SipraMtdRCategappCategoriDAO sipraMtdRCategappCategoriDAO)
 {
  this.sipraMtdRCategappCategoriDAO = sipraMtdRCategappCategoriDAO;
 }

 public SipraMtdRCategappCategoriDAO getSipraMtdRCategappCategoriDAO()
 {
  return this.sipraMtdRCategappCategoriDAO;
 }

 public void setSipraMtdRCategoriaMtdDAO(SipraMtdRCategoriaMtdDAO sipraMtdRCategoriaMtdDAO)
 {
  this.sipraMtdRCategoriaMtdDAO = sipraMtdRCategoriaMtdDAO;
 }

 public SipraMtdRCategoriaMtdDAO getSipraMtdRCategoriaMtdDAO()
 {
  return this.sipraMtdRCategoriaMtdDAO;
 }

 public void setSipraMtdRParolachiaveMtdDAO(SipraMtdRParolachiaveMtdDAO sipraMtdRParolachiaveMtdDAO)
 {
  this.sipraMtdRParolachiaveMtdDAO = sipraMtdRParolachiaveMtdDAO;
 }

 public SipraMtdRParolachiaveMtdDAO getSipraMtdRParolachiaveMtdDAO()
 {
  return this.sipraMtdRParolachiaveMtdDAO;
 }

 public void setSipraMtdTCategoriaDAO(SipraMtdTCategoriaDAO sipraMtdTCategoriaDAO)
 {
  this.sipraMtdTCategoriaDAO = sipraMtdTCategoriaDAO;
 }

 public SipraMtdTCategoriaDAO getSipraMtdTCategoriaDAO()
 {
  return this.sipraMtdTCategoriaDAO;
 }

 public void setSipraMtdTCategoriaApplDAO(SipraMtdTCategoriaApplDAO sipraMtdTCategoriaApplDAO)
 {
  this.sipraMtdTCategoriaApplDAO = sipraMtdTCategoriaApplDAO;
 }

 public SipraMtdTCategoriaApplDAO getSipraMtdTCategoriaApplDAO()
 {
  return this.sipraMtdTCategoriaApplDAO;
 }

 public void setSipraMtdTDettlogDAO(SipraMtdTDettlogDAO sipraMtdTDettlogDAO)
 {
  this.sipraMtdTDettlogDAO = sipraMtdTDettlogDAO;
 }

 public SipraMtdTDettlogDAO getSipraMtdTDettlogDAO()
 {
  return this.sipraMtdTDettlogDAO;
 }

 public void setSipraMtdTFunzioneDAO(SipraMtdTFunzioneDAO sipraMtdTFunzioneDAO)
 {
  this.sipraMtdTFunzioneDAO = sipraMtdTFunzioneDAO;
 }

 public SipraMtdTFunzioneDAO getSipraMtdTFunzioneDAO()
 {
  return this.sipraMtdTFunzioneDAO;
 }

 public void setSipraMtdTLogDAO(SipraMtdTLogDAO sipraMtdTLogDAO)
 {
  this.sipraMtdTLogDAO = sipraMtdTLogDAO;
 }

 public SipraMtdTLogDAO getSipraMtdTLogDAO()
 {
  return this.sipraMtdTLogDAO;
 }

 public void setSipraMtdTMetadatoDAO(SipraMtdTMetadatoDAO sipraMtdTMetadatoDAO)
 {
  this.sipraMtdTMetadatoDAO = sipraMtdTMetadatoDAO;
 }

 public SipraMtdTMetadatoDAO getSipraMtdTMetadatoDAO()
 {
  return this.sipraMtdTMetadatoDAO;
 }

 public void setSipraMtdTMtdCswDAO(SipraMtdTMtdCswDAO sipraMtdTMtdCswDAO)
 {
  this.sipraMtdTMtdCswDAO = sipraMtdTMtdCswDAO;
 }

 public SipraMtdTMtdCswDAO getSipraMtdTMtdCswDAO()
 {
  return this.sipraMtdTMtdCswDAO;
 }

 public void setSipraMtdTMtdPlusDAO(SipraMtdTMtdPlusDAO sipraMtdTMtdPlusDAO)
 {
  this.sipraMtdTMtdPlusDAO = sipraMtdTMtdPlusDAO;
 }

 public SipraMtdTMtdPlusDAO getSipraMtdTMtdPlusDAO()
 {
  return this.sipraMtdTMtdPlusDAO;
 }

 public void setSipraMtdTNewsHomePageDAO(SipraMtdTNewsHomePageDAO sipraMtdTNewsHomePageDAO)
 {
  this.sipraMtdTNewsHomePageDAO = sipraMtdTNewsHomePageDAO;
 }

 public SipraMtdTNewsHomePageDAO getSipraMtdTNewsHomePageDAO()
 {
  return this.sipraMtdTNewsHomePageDAO;
 }

 public void setSipraMtdTParolaChiaveDAO(SipraMtdTParolaChiaveDAO sipraMtdTParolaChiaveDAO)
 {
  this.sipraMtdTParolaChiaveDAO = sipraMtdTParolaChiaveDAO;
 }

 public SipraMtdTParolaChiaveDAO getSipraMtdTParolaChiaveDAO()
 {
  return this.sipraMtdTParolaChiaveDAO;
 }

 public void setSipraMtdTStoricoFunzioneDAO(SipraMtdTStoricoFunzioneDAO sipraMtdTStoricoFunzioneDAO)
 {
  this.sipraMtdTStoricoFunzioneDAO = sipraMtdTStoricoFunzioneDAO;
 }

 public SipraMtdTStoricoFunzioneDAO getSipraMtdTStoricoFunzioneDAO()
 {
  return this.sipraMtdTStoricoFunzioneDAO;
 }

 public void setSipraMtdTStoricoMtdCswDAO(SipraMtdTStoricoMtdCswDAO sipraMtdTStoricoMtdCswDAO)
 {
  this.sipraMtdTStoricoMtdCswDAO = sipraMtdTStoricoMtdCswDAO;
 }

 public SipraMtdTStoricoMtdCswDAO getSipraMtdTStoricoMtdCswDAO()
 {
  return this.sipraMtdTStoricoMtdCswDAO;
 }

 public void setSipraMtdTTestiHomePageDAO(SipraMtdTTestiHomePageDAO sipraMtdTTestiHomePageDAO)
 {
  this.sipraMtdTTestiHomePageDAO = sipraMtdTTestiHomePageDAO;
 }

 public SipraMtdTTestiHomePageDAO getSipraMtdTTestiHomePageDAO()
 {
  return this.sipraMtdTTestiHomePageDAO;
 }


 // CUSTOM BEGIN
 private InfoBoxDAO infoBoxDAO;

 public InfoBoxDAO getInfoBoxDAO() {
  return infoBoxDAO;
 }

 public void setInfoBoxDAO(InfoBoxDAO infoBoxDAO) {
  this.infoBoxDAO = infoBoxDAO;
 }
 // CUSTOM END
}
