/*
 * Created on 25 nov 2016 ( Time 10:35:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTDettlog;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * SipraMtdTDettlog DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdTDettlogDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idDettLog
	 * @return the bean found or null if not found 
	 */
	public SipraMtdTDettlog findByPK(Integer idDettLog);

	public List<SipraMtdTDettlog> findAll();
	
	public List<SipraMtdTDettlog> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdTDettlog> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdTDettlog> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdTDettlog bean);

	public void update(SipraMtdTDettlog bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idDettLog);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdTDettlog> getRowMapper();
}
