/*
 * Created on 25 nov 2016 ( Time 10:35:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTMtdCsw;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * SipraMtdTMtdCsw DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdTMtdCswDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idMetadato
	 * @return the bean found or null if not found 
	 */
	public SipraMtdTMtdCsw findByPK(Integer idMetadato);

	public List<SipraMtdTMtdCsw> findAll();
	
	public List<SipraMtdTMtdCsw> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdTMtdCsw> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdTMtdCsw> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdTMtdCsw bean);

	public void update(SipraMtdTMtdCsw bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idMetadato);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdTMtdCsw> getRowMapper();
}
