/*
 * Created on 25 nov 2016 ( Time 10:35:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdTNewsHomePage;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;


import java.math.BigDecimal;
import java.util.Date;


/**
 * SipraMtdTNewsHomePage DAO interface
 * 
 * @author Telosys Tools
 */
public interface SipraMtdTNewsHomePageDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idNews
	 * @return the bean found or null if not found 
	 */
	public SipraMtdTNewsHomePage findByPK(Integer idNews);

	public List<SipraMtdTNewsHomePage> findAll();
	
	public List<SipraMtdTNewsHomePage> findByCriteria(java.util.Map<String, Object> params);
	public List<SipraMtdTNewsHomePage> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<SipraMtdTNewsHomePage> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(SipraMtdTNewsHomePage bean);

	public void update(SipraMtdTNewsHomePage bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idNews);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<SipraMtdTNewsHomePage> getRowMapper();
}
