/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;


/**
 * Java bean for 'SipraMtdRParolachiaveMtd' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdRParolachiaveMtd implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_metadato int4 
    private Integer idMetadato;
    // DB : id_parola_chiave int4 
    private Integer idParolaChiave;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdMetadato( Integer idMetadato ) {
        this.idMetadato = idMetadato ;
    }

    public Integer getIdMetadato() {
        return this.idMetadato;
    }

    public void setIdParolaChiave( Integer idParolaChiave ) {
        this.idParolaChiave = idParolaChiave ;
    }

    public Integer getIdParolaChiave() {
        return this.idParolaChiave;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idMetadato);
        sb.append("|");
        sb.append(idParolaChiave);
        return sb.toString(); 
    } 


}
