/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;


/**
 * Java bean for 'SipraMtdDTipoOggetto' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdDTipoOggetto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_tipo_oggetto int4 
    private Integer idTipoOggetto;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : des_tipo_oggetto varchar 
    private String desTipoOggetto;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdTipoOggetto( Integer idTipoOggetto ) {
        this.idTipoOggetto = idTipoOggetto ;
    }

    public Integer getIdTipoOggetto() {
        return this.idTipoOggetto;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesTipoOggetto( String desTipoOggetto ) {
        this.desTipoOggetto = desTipoOggetto;
    }
    public String getDesTipoOggetto() {
        return this.desTipoOggetto;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTipoOggetto);
        sb.append("|");
        sb.append(desTipoOggetto);
        return sb.toString(); 
    } 


}
