/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;


/**
 * Java bean for 'SipraMtdDStandardEspos' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdDStandardEspos implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_standard_espos int4 
    private Integer idStandardEspos;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : des_standard_espos varchar 
    private String desStandardEspos;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdStandardEspos( Integer idStandardEspos ) {
        this.idStandardEspos = idStandardEspos ;
    }

    public Integer getIdStandardEspos() {
        return this.idStandardEspos;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesStandardEspos( String desStandardEspos ) {
        this.desStandardEspos = desStandardEspos;
    }
    public String getDesStandardEspos() {
        return this.desStandardEspos;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idStandardEspos);
        sb.append("|");
        sb.append(desStandardEspos);
        return sb.toString(); 
    } 


}
