/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;


/**
 * Java bean for 'SipraMtdDLingua' entity
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdDLingua implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_lingua int4 
    private Integer idLingua;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : des_lingua varchar 
    private String desLingua;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdLingua( Integer idLingua ) {
        this.idLingua = idLingua ;
    }

    public Integer getIdLingua() {
        return this.idLingua;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesLingua( String desLingua ) {
        this.desLingua = desLingua;
    }
    public String getDesLingua() {
        return this.desLingua;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idLingua);
        sb.append("|");
        sb.append(desLingua);
        return sb.toString(); 
    } 


}
