/**
 * Copyright 2016, GeoSolutions Sas.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
    plugins: {
        // product plugins
        AboutPlugin: require('../MapStore2/web/client/product/plugins/About'),
        AttributionPlugin: require('../MapStore2/web/client/product/plugins/Attribution'),
        ExamplesPlugin: require('../MapStore2/web/client/product/plugins/Examples'),
        FooterPlugin: require('../MapStore2/web/client/product/plugins/Footer'),
        ForkPlugin: require('../MapStore2/web/client/product/plugins/Fork'),
        HeaderPlugin: require('../MapStore2/web/client/product/plugins/Header'),
        HomeDescriptionPlugin: require('../MapStore2/web/client/product/plugins/HomeDescription'),
        MadeWithLovePlugin: require('../MapStore2/web/client/product/plugins/MadeWithLove'),
        MailingListsPlugin: require('../MapStore2/web/client/product/plugins/MailingLists'),
        MapTypePlugin: require('../MapStore2/web/client/product/plugins/MapType'),
        NavMenu: require('../MapStore2/web/client/product/plugins/NavMenu'),
        // framework plugins
        AddGroupPlugin: require('../MapStore2/web/client/plugins/AddGroup').default,
        AnnotationsPlugin: require('../MapStore2/web/client/plugins/Annotations'),
        AutoMapUpdatePlugin: require('../MapStore2/web/client/plugins/AutoMapUpdate'),
        BackgroundSelectorPlugin: require('../MapStore2/web/client/plugins/BackgroundSelector'),
        BackgroundSwitcherPlugin: require('../MapStore2/web/client/plugins/BackgroundSwitcher'),
        BurgerMenuPlugin: require('../MapStore2/web/client/plugins/BurgerMenu'),
        CRSSelectorPlugin: require('../MapStore2/web/client/plugins/CRSSelector'),
        ContentTabs: require('../MapStore2/web/client/plugins/ContentTabs'),
        ContextPlugin: require('../MapStore2/web/client/plugins/Context').default,
        ContextCreatorPlugin: require('../MapStore2/web/client/plugins/ContextCreator').default,
        ContextManagerPlugin: require('../MapStore2/web/client/plugins/contextmanager/ContextManager').default,
        CookiePlugin: require('../MapStore2/web/client/plugins/Cookie'),
        CreateNewMapPlugin: require('../MapStore2/web/client/plugins/CreateNewMap').default,
        Dashboard: require('../MapStore2/web/client/plugins/Dashboard'),
        DashboardEditor: require('../MapStore2/web/client/plugins/DashboardEditor'),
        DashboardsPlugin: require('../MapStore2/web/client/plugins/Dashboards'),
        DetailsPlugin: require('../MapStore2/web/client/plugins/Details'),
        DrawerMenuPlugin: require('../MapStore2/web/client/plugins/DrawerMenu'),
        ExpanderPlugin: require('../MapStore2/web/client/plugins/Expander'),
        FeatureEditorPlugin: require('../MapStore2/web/client/plugins/FeatureEditor').default,
        FeaturedMaps: require('../MapStore2/web/client/plugins/FeaturedMaps'),
        FeedbackMaskPlugin: require('../MapStore2/web/client/plugins/FeedbackMask'),
        FilterLayerPlugin: require('../MapStore2/web/client/plugins/FilterLayer').default,
        FloatingLegendPlugin: require('../MapStore2/web/client/plugins/FloatingLegend'),
        FullScreenPlugin: require('../MapStore2/web/client/plugins/FullScreen'),
        GeoStoryPlugin: require('../MapStore2/web/client/plugins/GeoStory').default,
        GeoStoriesPlugin: require('../MapStore2/web/client/plugins/GeoStories'),
        GeoStoryEditorPlugin: require('../MapStore2/web/client/plugins/GeoStoryEditor').default,
        GeoStorySavePlugin: require('../MapStore2/web/client/plugins/GeoStorySave').GeoStorySave,
        GeoStorySaveAsPlugin: require('../MapStore2/web/client/plugins/GeoStorySave').GeoStorySaveAs,
        DashboardSavePlugin: require('../MapStore2/web/client/plugins/DashboardSave').DashboardSave,
        DashboardSaveAsPlugin: require('../MapStore2/web/client/plugins/DashboardSave').DashboardSaveAs,
        GeoStoryNavigationPlugin: require('../MapStore2/web/client/plugins/GeoStoryNavigation').default,
        GlobeViewSwitcherPlugin: require('../MapStore2/web/client/plugins/GlobeViewSwitcher'),
        GoFull: require('../MapStore2/web/client/plugins/GoFull'),
        GridContainerPlugin: require('../MapStore2/web/client/plugins/GridContainer'),
        GroupManagerPlugin: require('../MapStore2/web/client/plugins/manager/GroupManager'),
        HelpLinkPlugin: require('../MapStore2/web/client/plugins/HelpLink').default,
        HelpPlugin: require('../MapStore2/web/client/plugins/Help'),
        HomePlugin: require('../MapStore2/web/client/plugins/Home'),
        IdentifyPlugin: require('../MapStore2/web/client/plugins/Identify'),
        LanguagePlugin: require('../MapStore2/web/client/plugins/Language'),
        LocatePlugin: require('../MapStore2/web/client/plugins/Locate'),
        LoginPlugin: require('../MapStore2/web/client/plugins/Login'),
        ManagerMenuPlugin: require('../MapStore2/web/client/plugins/manager/ManagerMenu'),
        ManagerPlugin: require('../MapStore2/web/client/plugins/manager/Manager'),
        MapEditorPlugin: require('../MapStore2/web/client/plugins/MapEditor').default,
        MapExportPlugin: require('../MapStore2/web/client/plugins/MapExport').default,
        MapFooterPlugin: require('../MapStore2/web/client/plugins/MapFooter'),
        MapImportPlugin: require('../MapStore2/web/client/plugins/MapImport'),
        MapLoadingPlugin: require('../MapStore2/web/client/plugins/MapLoading'),
        MapPlugin: require('../MapStore2/web/client/plugins/Map'),
        MapSearchPlugin: require('../MapStore2/web/client/plugins/MapSearch'),
        MapsPlugin: require('../MapStore2/web/client/plugins/Maps'),
        MapCatalogPlugin: require('../MapStore2/web/client/plugins/MapCatalog').default,
        MapTemplatesPlugin: require('../MapStore2/web/client/plugins/MapTemplates').default,
        MeasurePlugin: require('../MapStore2/web/client/plugins/Measure'),
        MediaEditorPlugin: require('../MapStore2/web/client/plugins/MediaEditor').default,
        MetadataExplorerPlugin: require('../MapStore2/web/client/plugins/MetadataExplorer'),
        MousePositionPlugin: require('../MapStore2/web/client/plugins/MousePosition'),
        NotificationsPlugin: require('../MapStore2/web/client/plugins/Notifications'),
        OmniBarPlugin: require('../MapStore2/web/client/plugins/OmniBar'),
        PlaybackPlugin: require('../MapStore2/web/client/plugins/Playback.jsx'),
        PrintPlugin: require('../MapStore2/web/client/plugins/Print'),
        QueryPanelPlugin: require('../MapStore2/web/client/plugins/QueryPanel'),
        RedirectPlugin: require('../MapStore2/web/client/plugins/Redirect'),
        RedoPlugin: require('../MapStore2/web/client/plugins/History'),
        RulesDataGridPlugin: require('../MapStore2/web/client/plugins/RulesDataGrid'),
        RulesEditorPlugin: require('../MapStore2/web/client/plugins/RulesEditor'),
        RulesManagerFooter: require('../MapStore2/web/client/plugins/RulesManagerFooter'),
        SavePlugin: require('../MapStore2/web/client/plugins/Save').default,
        SaveAsPlugin: require('../MapStore2/web/client/plugins/SaveAs').default,
        SaveStoryPlugin: require('../MapStore2/web/client/plugins/GeoStorySave'),
        ScaleBoxPlugin: require('../MapStore2/web/client/plugins/ScaleBox'),
        ScrollTopPlugin: require('../MapStore2/web/client/plugins/ScrollTop'),
        SearchPlugin: require('../MapStore2/web/client/plugins/Search'),
        SearchServicesConfigPlugin: require('../MapStore2/web/client/plugins/SearchServicesConfig'),
        SearchByBookmarkPlugin: require('../MapStore2/web/client/plugins/SearchByBookmark').default,
        SettingsPlugin: require('../MapStore2/web/client/plugins/Settings'),
        SharePlugin: require('../MapStore2/web/client/plugins/Share'),
        SnapshotPlugin: require('../MapStore2/web/client/plugins/Snapshot'),
        StyleEditorPlugin: require('../MapStore2/web/client/plugins/StyleEditor'),
        ThematicLayerPlugin: require('../MapStore2/web/client/plugins/ThematicLayer'),
        ThemeSwitcherPlugin: require('../MapStore2/web/client/plugins/ThemeSwitcher'),
        TimelinePlugin: require('../MapStore2/web/client/plugins/Timeline'),
        ToolbarPlugin: require('../MapStore2/web/client/plugins/Toolbar'),
        TutorialPlugin: require('../MapStore2/web/client/plugins/Tutorial'),
        UndoPlugin: require('../MapStore2/web/client/plugins/History'),
        UserManagerPlugin: require('../MapStore2/web/client/plugins/manager/UserManager'),
        UserExtensionsPlugin: require('../MapStore2/web/client/plugins/UserExtensions').default,
        UserSessionPlugin: require('../MapStore2/web/client/plugins/UserSession').default,
        VersionPlugin: require('../MapStore2/web/client/plugins/Version'),
        WFSDownloadPlugin: require('../MapStore2/web/client/plugins/WFSDownload'),
        WidgetsBuilderPlugin: require('../MapStore2/web/client/plugins/WidgetsBuilder').default,
        WidgetsPlugin: require('../MapStore2/web/client/plugins/Widgets').default,
        WidgetsTrayPlugin: require('../MapStore2/web/client/plugins/WidgetsTray').default,
        ZoomAllPlugin: require('../MapStore2/web/client/plugins/ZoomAll'),
        ZoomInPlugin: require('../MapStore2/web/client/plugins/ZoomIn'),
        ZoomOutPlugin: require('../MapStore2/web/client/plugins/ZoomOut'),

        // project plugins
        InfoPlugin: require('./plugins/InfoPlugin'),
        TOCPlugin: require('./plugins/SIRATOC'),
        CatalogPlugin: require('./plugins/SiraCatalog')
    },
    requires: {
        ReactSwipe: require('react-swipeable-views').default,
        SwipeHeader: require('../MapStore2/web/client/components/data/identify/SwipeHeader')
    }
};
